#!/usr/bin/env node
/* Auto-generated by the Manga admin panel. Builds a WebView APK project. */
const fs = require('fs');
const path = require('path');

let cfg = {};
try {
  cfg = JSON.parse(fs.readFileSync('apk-config.json', 'utf8'));
} catch {
  cfg = {};
}

const env = process.env;
const appName = env.APP_NAME || cfg.app_name || 'Manga Reader';
const pkg = cfg.package_id || env.FALLBACK_PACKAGE || 'com.mangareader.app';
const versionName = env.VERSION_NAME || cfg.version_name || '1.0.0';
const versionCode = parseInt(env.VERSION_CODE || cfg.version_code || '1', 10) || 1;
const websiteUrl = env.WEBSITE_URL || cfg.website_url || '';
const color = cfg.primary_color || '#e23636';
const minSdk = parseInt(cfg.min_sdk || 21, 10) || 21;
const targetSdk = parseInt(cfg.target_sdk || 34, 10) || 34;

const write = (p, content) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  console.log('wrote', p);
};

const pkgPath = pkg.split('.').join('/');

write('settings.gradle', [
  'pluginManagement {',
  '  repositories { google(); mavenCentral(); gradlePluginPortal() }',
  '}',
  'dependencyResolutionManagement {',
  '  repositories { google(); mavenCentral() }',
  '}',
  "rootProject.name = 'MangaApp'",
  "include ':app'",
].join('\n'));

write('build.gradle', [
  'plugins {',
  "  id 'com.android.application' version '8.5.2' apply false",
  '}',
].join('\n'));

write('gradle.properties', [
  'org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g',
  'android.useAndroidX=true',
  'android.nonTransitiveRClass=true',
].join('\n'));

write('app/build.gradle', [
  'plugins {',
  "  id 'com.android.application'",
  '}',
  'android {',
  "  namespace '" + pkg + "'",
  '  compileSdk ' + targetSdk,
  '  defaultConfig {',
  "    applicationId '" + pkg + "'",
  '    minSdk ' + minSdk,
  '    targetSdk ' + targetSdk,
  '    versionCode ' + versionCode,
  "    versionName '" + versionName + "'",
  '  }',
  '  buildTypes {',
  '    release {',
  '      minifyEnabled false',
  '      signingConfig signingConfigs.debug',
  '    }',
  '  }',
  '  compileOptions {',
  '    sourceCompatibility JavaVersion.VERSION_17',
  '    targetCompatibility JavaVersion.VERSION_17',
  '  }',
  '}',
  'dependencies {',
  "  implementation 'androidx.appcompat:appcompat:1.6.1'",
  '}',
].join('\n'));

write('app/src/main/AndroidManifest.xml', [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<manifest xmlns:android="http://schemas.android.com/apk/res/android">',
  '  <uses-permission android:name="android.permission.INTERNET" />',
  '  <application',
  '    android:label="@string/app_name"',
  '    android:icon="@drawable/ic_launcher"',
  '    android:theme="@style/AppTheme"',
  '    android:usesCleartextTraffic="true">',
  '    <activity',
  '      android:name=".MainActivity"',
  '      android:exported="true"',
  '      android:configChanges="orientation|screenSize|keyboardHidden">',
  '      <intent-filter>',
  '        <action android:name="android.intent.action.MAIN" />',
  '        <category android:name="android.intent.category.LAUNCHER" />',
  '      </intent-filter>',
  '    </activity>',
  '  </application>',
  '</manifest>',
].join('\n'));

write('app/src/main/res/values/strings.xml', [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<resources>',
  '  <string name="app_name">' + appName.replace(/&/g, '&amp;').replace(/</g, '&lt;') + '</string>',
  '</resources>',
].join('\n'));

write('app/src/main/res/values/colors.xml', [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<resources>',
  '  <color name="primary">' + color + '</color>',
  '</resources>',
].join('\n'));

write('app/src/main/res/values/styles.xml', [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<resources>',
  '  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">',
  '    <item name="colorPrimary">@color/primary</item>',
  '    <item name="android:windowBackground">@color/primary</item>',
  '  </style>',
  '</resources>',
].join('\n'));

write('app/src/main/res/drawable/ic_launcher.xml', [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">',
  '  <solid android:color="@color/primary" />',
  '</shape>',
].join('\n'));

const safeUrl = (websiteUrl || 'https://example.com').replace(/"/g, '');
write('app/src/main/java/' + pkgPath + '/MainActivity.java', [
  'package ' + pkg + ';',
  '',
  'import android.app.Activity;',
  'import android.os.Bundle;',
  'import android.webkit.WebSettings;',
  'import android.webkit.WebView;',
  'import android.webkit.WebViewClient;',
  '',
  'public class MainActivity extends Activity {',
  '  private WebView web;',
  '',
  '  @Override',
  '  protected void onCreate(Bundle state) {',
  '    super.onCreate(state);',
  '    web = new WebView(this);',
  '    WebSettings s = web.getSettings();',
  '    s.setJavaScriptEnabled(true);',
  '    s.setDomStorageEnabled(true);',
  '    s.setLoadWithOverviewMode(true);',
  '    s.setUseWideViewPort(true);',
  '    web.setWebViewClient(new WebViewClient());',
  '    setContentView(web);',
  '    web.loadUrl("' + safeUrl + '");',
  '  }',
  '',
  '  @Override',
  '  public void onBackPressed() {',
  '    if (web != null && web.canGoBack()) {',
  '      web.goBack();',
  '    } else {',
  '      super.onBackPressed();',
  '    }',
  '  }',
  '}',
].join('\n'));

console.log('Android project generated for ' + pkg + ' v' + versionName + ' (' + versionCode + ')');
