#!/usr/bin/env node
/* Auto-generated by the Manga admin panel. Builds a minimal WebView APK project. */
const fs = require('fs');
const path = require('path');

let cfg = {};
try {
  cfg = JSON.parse(fs.readFileSync('apk-config.json', 'utf8'));
} catch {
  cfg = {};
}

const env = process.env;

const nameCandidates = [env.APP_NAME, cfg.app_name, cfg.site_name]
  .map((v) => String(v || '').trim())
  .filter((v) => v && !/^(app|application|android|manga)$/i.test(v));
const rawAppName = nameCandidates[0] || String(cfg.site_name || cfg.app_name || 'Manga').trim();
const appName =
  rawAppName
    .replace(/\s*(Reader|App|Application|Android)\s*$/i, '')
    .replace(/\s*[-_|]\s*(Reader|App|Application)\s*$/i, '')
    .trim() || 'Manga';

let pkg = String(cfg.package_id || env.FALLBACK_PACKAGE || 'com.mangareader.app').trim();
if (!/^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$/.test(pkg)) {
  console.warn('Invalid package_id, falling back to com.mangareader.app');
  pkg = 'com.mangareader.app';
}

const versionName = String(env.VERSION_NAME || cfg.version_name || '1.0.0')
  .replace(/'/g, '')
  .replace(/"/g, '')
  .replace(/[^\w.-]/g, '');
const versionCode = Math.max(1, parseInt(env.VERSION_CODE || cfg.version_code || '1', 10) || 1);
const websiteUrl = String(env.WEBSITE_URL || cfg.website_url || 'https://example.com').trim();
let color = String(cfg.primary_color || '#E23636').trim();
if (!/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/.test(color)) {
  color = '#E23636';
}
if (color.length === 4) {
  color = '#' + color[1] + color[1] + color[2] + color[2] + color[3] + color[3];
}
if (color.length === 9) {
  color = '#' + color.slice(3);
}

const minSdk = Math.max(21, parseInt(cfg.min_sdk || 24, 10) || 24);
const targetSdk = Math.min(34, Math.max(minSdk, parseInt(cfg.target_sdk || 34, 10) || 34));
const compileSdk = 34;

// AGP 8.2.2 + Gradle 8.2 — stable on ubuntu-latest
const AGP_VERSION = '8.2.2';
const GRADLE_VERSION = '8.2';

const writeText = (p, content) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const body = String(content);
  fs.writeFileSync(p, body.endsWith('\n') ? body : body + '\n', 'utf8');
  console.log('wrote', p);
};

const xmlEscape = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const pkgPath = pkg.split('.').join('/');
const baseUrl = websiteUrl || 'https://example.com';
const appUrl =
  baseUrl +
  (baseUrl.includes('?') ? '&' : '?') +
  'app=1&app_version=' +
  encodeURIComponent(versionName) +
  '&app_code=' +
  versionCode;
const safeUrl = appUrl.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

function writeVectorIcon() {
  writeText(
    'app/src/main/res/drawable/ic_launcher.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
      '    android:width="108dp"',
      '    android:height="108dp"',
      '    android:viewportWidth="108"',
      '    android:viewportHeight="108">',
      '    <path',
      '        android:fillColor="' + color + '"',
      '        android:pathData="M0,0h108v108h-108z" />',
      '    <path',
      '        android:fillColor="#FFFFFF"',
      '        android:pathData="M30,30h48v48h-48z" />',
      '</vector>',
    ].join('\n'),
  );
}

const MIPMAP_BUCKETS = [
  { dir: 'mipmap-ldpi', size: 36 },
  { dir: 'mipmap-mdpi', size: 48 },
  { dir: 'mipmap-hdpi', size: 72 },
  { dir: 'mipmap-xhdpi', size: 96 },
  { dir: 'mipmap-xxhdpi', size: 144 },
  { dir: 'mipmap-xxxhdpi', size: 192 },
];

function isPngBuffer(buf) {
  return (
    Buffer.isBuffer(buf) &&
    buf.length >= 24 &&
    buf[0] === 0x89 &&
    buf[1] === 0x50 &&
    buf[2] === 0x4e &&
    buf[3] === 0x47 &&
    buf[4] === 0x0d &&
    buf[5] === 0x0a &&
    buf[6] === 0x1a &&
    buf[7] === 0x0a
  );
}

function readPngIhdr(buf) {
  // PNG signature (8) + IHDR length(4) + type(4) + data…
  if (!isPngBuffer(buf)) return null;
  const type = buf.toString('ascii', 12, 16);
  if (type !== 'IHDR') return null;
  const width = buf.readUInt32BE(16);
  const height = buf.readUInt32BE(20);
  const bitDepth = buf[24];
  const colorType = buf[25];
  return { width, height, bitDepth, colorType };
}

/**
 * Decode website logo from apk-icon.b64 and place launcher PNGs in every
 * mipmap density bucket. Falls back to vector drawable on any failure.
 * Returns icon resource ref: '@mipmap/ic_launcher' or '@drawable/ic_launcher'.
 */
function installLauncherIcon() {
  const MAX_BYTES = 2 * 1024 * 1024;
  const MAX_DIM = 2048;

  let pngBuf = null;
  if (fs.existsSync('apk-icon.b64')) {
    try {
      const b64 = fs.readFileSync('apk-icon.b64', 'utf8').replace(/\s+/g, '');
      if (b64.length > 0) {
        pngBuf = Buffer.from(b64, 'base64');
        console.log('apk-icon.b64 decoded to', pngBuf.length, 'bytes');
      }
    } catch (e) {
      console.warn('apk-icon.b64 read/decode failed:', e.message);
      pngBuf = null;
    }
  } else {
    console.log('apk-icon.b64 not found — vector launcher fallback');
  }

  if (!pngBuf || !isPngBuffer(pngBuf)) {
    if (pngBuf) console.warn('apk-icon.b64 is not a valid PNG — vector fallback');
    writeVectorIcon();
    return '@drawable/ic_launcher';
  }

  if (pngBuf.length > MAX_BYTES) {
    console.warn(
      'logo PNG too large (' + pngBuf.length + ' > ' + MAX_BYTES + ') — vector fallback',
    );
    writeVectorIcon();
    return '@drawable/ic_launcher';
  }

  const ihdr = readPngIhdr(pngBuf);
  if (!ihdr || !ihdr.width || !ihdr.height) {
    console.warn('PNG IHDR unreadable — vector fallback');
    writeVectorIcon();
    return '@drawable/ic_launcher';
  }
  if (ihdr.width > MAX_DIM || ihdr.height > MAX_DIM) {
    console.warn(
      'PNG dimensions ' + ihdr.width + 'x' + ihdr.height + ' too large — vector fallback',
    );
    writeVectorIcon();
    return '@drawable/ic_launcher';
  }
  // Reject exotic types that sometimes trip older aapt; allow 2/3/4/6 (gray, RGB, palette, RGBA)
  if (![0, 2, 3, 4, 6].includes(ihdr.colorType)) {
    console.warn('PNG colorType ' + ihdr.colorType + ' unsupported — vector fallback');
    writeVectorIcon();
    return '@drawable/ic_launcher';
  }

  // Same validated PNG in every density bucket. Android scales for the device;
  // avoids needing a native image resizer inside the CI generator.
  for (const bucket of MIPMAP_BUCKETS) {
    const dir = path.join('app/src/main/res', bucket.dir);
    fs.mkdirSync(dir, { recursive: true });
    const out = path.join(dir, 'ic_launcher.png');
    fs.writeFileSync(out, pngBuf);
    // Verify magic still intact after write
    const check = fs.readFileSync(out);
    if (!isPngBuffer(check)) {
      console.warn('mipmap write corrupt at', out, '— vector fallback');
      try {
        fs.rmSync('app/src/main/res/mipmap-ldpi', { recursive: true, force: true });
        fs.rmSync('app/src/main/res/mipmap-mdpi', { recursive: true, force: true });
        fs.rmSync('app/src/main/res/mipmap-hdpi', { recursive: true, force: true });
        fs.rmSync('app/src/main/res/mipmap-xhdpi', { recursive: true, force: true });
        fs.rmSync('app/src/main/res/mipmap-xxhdpi', { recursive: true, force: true });
        fs.rmSync('app/src/main/res/mipmap-xxxhdpi', { recursive: true, force: true });
      } catch {
        /* ignore */
      }
      writeVectorIcon();
      return '@drawable/ic_launcher';
    }
    console.log('wrote', out, '(' + check.length + ' bytes, src ' + ihdr.width + 'x' + ihdr.height + ')');
  }

  // Keep a drawable vector as secondary roundIcon fallback only if needed — not used when mipmap OK.
  console.log(
    'Launcher icon installed from website logo PNG (' +
      ihdr.width +
      'x' +
      ihdr.height +
      ', ' +
      pngBuf.length +
      ' bytes) → @mipmap/ic_launcher',
  );
  return '@mipmap/ic_launcher';
}

(async () => {
  try {
    fs.rmSync('app', { recursive: true, force: true });
  } catch {
    /* ignore */
  }
  for (const f of [
    'settings.gradle',
    'build.gradle',
    'gradle.properties',
    'local.properties',
    'gradlew',
    'gradlew.bat',
  ]) {
    try {
      fs.rmSync(f, { force: true });
    } catch {
      /* ignore */
    }
  }
  try {
    fs.rmSync('gradle', { recursive: true, force: true });
  } catch {
    /* ignore */
  }

  writeText(
    'settings.gradle',
    [
      'pluginManagement {',
      '    repositories {',
      '        google()',
      '        mavenCentral()',
      '        gradlePluginPortal()',
      '    }',
      '}',
      'dependencyResolutionManagement {',
      '    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)',
      '    repositories {',
      '        google()',
      '        mavenCentral()',
      '    }',
      '}',
      "rootProject.name = 'MangaApp'",
      "include ':app'",
    ].join('\n'),
  );

  writeText(
    'build.gradle',
    [
      'plugins {',
      "    id 'com.android.application' version '" + AGP_VERSION + "' apply false",
      '}',
    ].join('\n'),
  );

  writeText(
    'gradle.properties',
    [
      'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m',
      'org.gradle.parallel=true',
      'org.gradle.caching=true',
      'org.gradle.configuration-cache=false',
      'org.gradle.daemon=false',
      'android.useAndroidX=true',
      'android.nonTransitiveRClass=true',
    ].join('\n'),
  );

  writeText(
    'gradle/wrapper/gradle-wrapper.properties',
    [
      'distributionBase=GRADLE_USER_HOME',
      'distributionPath=wrapper/dists',
      'distributionUrl=https\\://services.gradle.org/distributions/gradle-' +
        GRADLE_VERSION +
        '-bin.zip',
      'networkTimeout=60000',
      'validateDistributionUrl=true',
      'zipStoreBase=GRADLE_USER_HOME',
      'zipStorePath=wrapper/dists',
    ].join('\n'),
  );

  const sdkDir = String(process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT || '').replace(
    /\\/g,
    '\\\\',
  );
  if (sdkDir) {
    writeText('local.properties', 'sdk.dir=' + sdkDir);
  } else {
    console.warn('ANDROID_HOME not set at generate time — Gradle will use env on build.');
  }

  // Use built-in debug signing for release so assembleRelease always produces
  // an installable APK without a custom keystore. Workflow creates
  // ~/.android/debug.keystore before the build. Optional release re-sign
  // happens later via apksigner when KEYSTORE_BASE64 is set.
  writeText(
    'app/build.gradle',
    [
      'plugins {',
      "    id 'com.android.application'",
      '}',
      '',
      'android {',
      "    namespace '" + pkg + "'",
      '    compileSdk ' + compileSdk,
      '',
      '    defaultConfig {',
      "        applicationId '" + pkg + "'",
      '        minSdk ' + minSdk,
      '        targetSdk ' + targetSdk,
      '        versionCode ' + versionCode,
      '        versionName "' + versionName + '"',
      '    }',
      '',
      '    buildTypes {',
      '        release {',
      '            minifyEnabled false',
      '            shrinkResources false',
      '            debuggable false',
      '            signingConfig signingConfigs.debug',
      '        }',
      '    }',
      '',
      '    compileOptions {',
      '        sourceCompatibility JavaVersion.VERSION_17',
      '        targetCompatibility JavaVersion.VERSION_17',
      '    }',
      '',
      '    packaging {',
      '        resources {',
      "            excludes += ['/META-INF/{AL2.0,LGPL2.1}', 'META-INF/DEPENDENCIES']",
      '        }',
      '    }',
      '',
      '    lint {',
      '        checkReleaseBuilds false',
      '        abortOnError false',
      '    }',
      '}',
      '',
      'dependencies {',
      '}',
    ].join('\n'),
  );

  writeText(
    'app/proguard-rules.pro',
    '# WebView\n-keepclassmembers class * {\n    @android.webkit.JavascriptInterface <methods>;\n}\n',
  );

  // Install website logo (apk-icon.b64 → mipmap PNG) before writing the manifest
  // so android:icon / android:roundIcon point at the real launcher asset.
  const iconRef = installLauncherIcon();

  writeText(
    'app/src/main/AndroidManifest.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<manifest xmlns:android="http://schemas.android.com/apk/res/android">',
      '',
      '    <uses-permission android:name="android.permission.INTERNET" />',
      '    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />',
      '',
      '    <application',
      '        android:allowBackup="true"',
      '        android:icon="' + iconRef + '"',
      '        android:roundIcon="' + iconRef + '"',
      '        android:label="@string/app_name"',
      '        android:supportsRtl="true"',
      '        android:theme="@style/Theme.MangaApp"',
      '        android:usesCleartextTraffic="true">',
      '',
      '        <activity',
      '            android:name=".MainActivity"',
      '            android:exported="true"',
      '            android:configChanges="orientation|screenSize|keyboardHidden|screenLayout|smallestScreenSize"',
      '            android:launchMode="singleTask"',
      '            android:windowSoftInputMode="adjustResize">',
      '            <intent-filter>',
      '                <action android:name="android.intent.action.MAIN" />',
      '                <category android:name="android.intent.category.LAUNCHER" />',
      '            </intent-filter>',
      '        </activity>',
      '    </application>',
      '</manifest>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/values/strings.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <string name="app_name">' + xmlEscape(appName) + '</string>',
      '</resources>',
    ].join('\n'),
  );

  // Platform Theme.Material attributes use the android: namespace.
  // Bare colorPrimary / colorPrimaryDark / colorAccent are AppCompat-only
  // and fail resource merge when dependencies {} is empty (no AndroidX).
  writeText(
    'app/src/main/res/values/colors.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <color name="primary">' + color + '</color>',
      '    <color name="primary_dark">' + color + '</color>',
      '    <color name="accent">' + color + '</color>',
      '    <color name="black">#FF000000</color>',
      '    <color name="white">#FFFFFFFF</color>',
      '    <color name="window_background">#FF000000</color>',
      '</resources>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/values/themes.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <style name="Theme.MangaApp" parent="@android:style/Theme.Material.Light.NoActionBar">',
      '        <item name="android:colorPrimary">@color/primary</item>',
      '        <item name="android:colorPrimaryDark">@color/primary_dark</item>',
      '        <item name="android:colorAccent">@color/accent</item>',
      '        <item name="android:statusBarColor">@color/primary_dark</item>',
      '        <item name="android:navigationBarColor">@color/black</item>',
      '        <item name="android:windowBackground">@color/window_background</item>',
      '        <item name="android:windowDrawsSystemBarBackgrounds">true</item>',
      '        <item name="android:textColorPrimary">@color/white</item>',
      '    </style>',
      '</resources>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/layout/activity_main.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"',
      '    android:layout_width="match_parent"',
      '    android:layout_height="match_parent"',
      '    android:background="@color/black">',
      '    <WebView',
      '        android:id="@+id/webview"',
      '        android:layout_width="match_parent"',
      '        android:layout_height="match_parent" />',
      '</FrameLayout>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/java/' + pkgPath + '/MainActivity.java',
    [
      'package ' + pkg + ';',
      '',
      'import android.annotation.SuppressLint;',
      'import android.os.Bundle;',
      'import android.webkit.WebChromeClient;',
      'import android.webkit.WebSettings;',
      'import android.webkit.WebView;',
      'import android.webkit.WebViewClient;',
      'import android.app.Activity;',
      '',
      'public class MainActivity extends Activity {',
      '    private WebView webView;',
      '',
      '    @Override',
      '    @SuppressLint("SetJavaScriptEnabled")',
      '    protected void onCreate(Bundle savedInstanceState) {',
      '        super.onCreate(savedInstanceState);',
      '        setContentView(R.layout.activity_main);',
      '        webView = (WebView) findViewById(R.id.webview);',
      '',
      '        WebSettings settings = webView.getSettings();',
      '        settings.setJavaScriptEnabled(true);',
      '        settings.setDomStorageEnabled(true);',
      '        settings.setLoadWithOverviewMode(true);',
      '        settings.setUseWideViewPort(true);',
      '        settings.setSupportZoom(false);',
      '        settings.setBuiltInZoomControls(false);',
      '        settings.setDisplayZoomControls(false);',
      '        settings.setMediaPlaybackRequiresUserGesture(false);',
      '        settings.setAllowFileAccess(false);',
      '        settings.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);',
      '        settings.setCacheMode(WebSettings.LOAD_DEFAULT);',
      '',
      '        webView.setWebViewClient(new WebViewClient());',
      '        webView.setWebChromeClient(new WebChromeClient());',
      '        webView.loadUrl("' + safeUrl + '");',
      '    }',
      '',
      '    @Override',
      '    @SuppressWarnings("deprecation")',
      '    public void onBackPressed() {',
      '        if (webView != null && webView.canGoBack()) {',
      '            webView.goBack();',
      '        } else {',
      '            super.onBackPressed();',
      '        }',
      '    }',
      '',
      '    @Override',
      '    protected void onDestroy() {',
      '        if (webView != null) {',
      '            webView.stopLoading();',
      '            webView.destroy();',
      '            webView = null;',
      '        }',
      '        super.onDestroy();',
      '    }',
      '}',
    ].join('\n'),
  );

  const mustExist = [
    'settings.gradle',
    'build.gradle',
    'app/build.gradle',
    'app/src/main/AndroidManifest.xml',
    'app/src/main/res/values/strings.xml',
    'app/src/main/res/values/colors.xml',
    'app/src/main/res/values/themes.xml',
    'app/src/main/res/layout/activity_main.xml',
    'app/src/main/java/' + pkgPath + '/MainActivity.java',
  ];
  for (const f of mustExist) {
    if (!fs.existsSync(f)) {
      console.error('Missing required file after generate:', f);
      process.exit(1);
    }
  }

  // Guard against AppCompat-only theme attrs (no AndroidX on the classpath).
  const themesBody = fs.readFileSync('app/src/main/res/values/themes.xml', 'utf8');
  if (/(?:name="colorPrimary"|name="colorPrimaryDark"|name="colorAccent")/.test(themesBody)) {
    console.error(
      'themes.xml still references AppCompat attrs (colorPrimary/colorPrimaryDark/colorAccent). Use android:color* instead.',
    );
    process.exit(1);
  }
  const colorsBody = fs.readFileSync('app/src/main/res/values/colors.xml', 'utf8');
  for (const c of ['primary', 'primary_dark', 'accent', 'black', 'white']) {
    if (!new RegExp('name="' + c + '"').test(colorsBody)) {
      console.error('colors.xml missing color:', c);
      process.exit(1);
    }
  }
  const hasMipmap = fs.existsSync('app/src/main/res/mipmap-hdpi/ic_launcher.png');
  const hasVector = fs.existsSync('app/src/main/res/drawable/ic_launcher.xml');
  if (!hasMipmap && !hasVector) {
    console.warn('No icon found — writing emergency vector');
    writeVectorIcon();
  }
  // Manifest must match installed assets
  const manifestPath = 'app/src/main/AndroidManifest.xml';
  let manifestBody = fs.readFileSync(manifestPath, 'utf8');
  if (hasMipmap) {
    manifestBody = manifestBody
      .replace(/android:icon="[^"]*"/g, 'android:icon="@mipmap/ic_launcher"')
      .replace(/android:roundIcon="[^"]*"/g, 'android:roundIcon="@mipmap/ic_launcher"');
    fs.writeFileSync(manifestPath, manifestBody.endsWith('\n') ? manifestBody : manifestBody + '\n', 'utf8');
  } else if (hasVector || fs.existsSync('app/src/main/res/drawable/ic_launcher.xml')) {
    manifestBody = manifestBody
      .replace(/android:icon="[^"]*"/g, 'android:icon="@drawable/ic_launcher"')
      .replace(/android:roundIcon="[^"]*"/g, 'android:roundIcon="@drawable/ic_launcher"');
    fs.writeFileSync(manifestPath, manifestBody.endsWith('\n') ? manifestBody : manifestBody + '\n', 'utf8');
  }

  const iconMode = hasMipmap ? 'mipmap-png' : 'vector';
  console.log(
    'Android project generated for ' +
      pkg +
      ' v' +
      versionName +
      ' (' +
      versionCode +
      ') url=' +
      websiteUrl +
      ' icon=' +
      iconMode +
      ' agp=' +
      AGP_VERSION +
      ' gradle=' +
      GRADLE_VERSION,
  );
})().catch((e) => {
  console.error('gen-android failed:', e);
  process.exit(1);
});
