#!/usr/bin/env node
/* Auto-generated by the Manga admin panel. Builds a minimal WebView APK project. */
const fs = require('fs');
const path = require('path');

let cfg = {};
try {
  cfg = JSON.parse(fs.readFileSync('apk-config.json', 'utf8'));
} catch {
  cfg = {};
}

const env = process.env;

// App name = website name exactly (no Reader/App/Application suffix).
const nameCandidates = [env.APP_NAME, cfg.app_name, cfg.site_name]
  .map((v) => String(v || '').trim())
  .filter((v) => v && !/^(app|application|android|manga)$/i.test(v));
const rawAppName = nameCandidates[0] || String(cfg.site_name || cfg.app_name || 'Manga').trim();
const appName =
  rawAppName
    .replace(/\s*(Reader|App|Application|Android)\s*$/i, '')
    .replace(/\s*[-_|]\s*(Reader|App|Application)\s*$/i, '')
    .trim() || 'Manga';

let pkg = String(cfg.package_id || env.FALLBACK_PACKAGE || 'com.mangareader.app').trim();
if (!/^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$/.test(pkg)) {
  console.warn('Invalid package_id, falling back to com.mangareader.app');
  pkg = 'com.mangareader.app';
}

const versionName = String(env.VERSION_NAME || cfg.version_name || '1.0.0')
  .replace(/'/g, '')
  .replace(/"/g, '');
const versionCode = Math.max(1, parseInt(env.VERSION_CODE || cfg.version_code || '1', 10) || 1);
const websiteUrl = String(env.WEBSITE_URL || cfg.website_url || 'https://example.com').trim();
const logoUrl = String(env.LOGO_URL || cfg.logo_url || '').trim();

let color = String(cfg.primary_color || '#E23636').trim();
// colors.xml only accepts #RGB / #ARGB / #RRGGBB / #AARRGGBB
if (!/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/.test(color)) {
  color = '#E23636';
}
// Normalize short hex
if (color.length === 4) {
  color =
    '#' +
    color[1] +
    color[1] +
    color[2] +
    color[2] +
    color[3] +
    color[3];
}

const minSdk = Math.max(21, parseInt(cfg.min_sdk || 24, 10) || 24);
const targetSdk = Math.min(34, Math.max(minSdk, parseInt(cfg.target_sdk || 34, 10) || 34));
const compileSdk = 34;

// AGP 8.2.2 + Gradle 8.2 — widely proven on ubuntu-latest GitHub runners
const AGP_VERSION = '8.2.2';
const GRADLE_VERSION = '8.2';

const writeText = (p, content) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const body = String(content);
  fs.writeFileSync(p, body.endsWith('\n') ? body : body + '\n', 'utf8');
  console.log('wrote', p);
};

const writeBinary = (p, buf) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, buf);
  console.log('wrote binary', p, '(' + buf.length + ' bytes)');
};

const xmlEscape = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const pkgPath = pkg.split('.').join('/');
const baseUrl = websiteUrl || 'https://example.com';
const appUrl =
  baseUrl +
  (baseUrl.includes('?') ? '&' : '?') +
  'app=1&app_version=' +
  encodeURIComponent(versionName) +
  '&app_code=' +
  versionCode;
const safeUrl = appUrl.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

let logoDownloaded = false;

function isPng(buf) {
  return (
    buf &&
    buf.length >= 100 &&
    buf[0] === 0x89 &&
    buf[1] === 0x50 &&
    buf[2] === 0x4e &&
    buf[3] === 0x47
  );
}

// AAPT2 often OOMs or fails on multi-MB launcher PNGs. Cap at 400KB.
const MAX_ICON_BYTES = 400 * 1024;

function installPngIcon(buf) {
  if (!isPng(buf)) {
    console.warn('Icon is not a valid PNG');
    return false;
  }
  if (buf.length > MAX_ICON_BYTES) {
    console.warn(
      'Icon is ' +
        buf.length +
        ' bytes (>' +
        MAX_ICON_BYTES +
        '); using vector fallback to avoid AAPT2 OOM.',
    );
    return false;
  }
  // Prefer mipmap-hdpi (standard launcher density). Avoid drawable-nodpi
  // which has caused resource linking issues with some AGP versions.
  writeBinary('app/src/main/res/mipmap-hdpi/ic_launcher.png', buf);
  writeBinary('app/src/main/res/mipmap-mdpi/ic_launcher.png', buf);
  writeBinary('app/src/main/res/mipmap-xhdpi/ic_launcher.png', buf);
  return true;
}

function localLogoIcon() {
  try {
    if (!fs.existsSync('apk-icon.b64')) return false;
    const b64 = fs.readFileSync('apk-icon.b64', 'utf8').replace(/\s+/g, '');
    if (b64.length < 100) return false;
    const buf = Buffer.from(b64, 'base64');
    if (!installPngIcon(buf)) return false;
    console.log('App icon set from committed website logo (' + buf.length + ' bytes).');
    return true;
  } catch (e) {
    console.warn('Local icon decode failed:', e.message);
    return false;
  }
}

async function downloadLogoIcon() {
  if (localLogoIcon()) return true;
  if (!logoUrl) return false;
  try {
    console.log('Downloading app icon from', logoUrl);
    const r = await fetch(logoUrl, { redirect: 'follow' });
    if (!r.ok) throw new Error('logo fetch failed: ' + r.status);
    const buf = Buffer.from(await r.arrayBuffer());
    if (!installPngIcon(buf)) return false;
    console.log('App icon set from website logo (' + buf.length + ' bytes).');
    return true;
  } catch (e) {
    console.warn('Logo download failed, using vector fallback:', e.message);
    return false;
  }
}

function writeVectorIcon() {
  writeText(
    'app/src/main/res/drawable/ic_launcher.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
      '    android:width="108dp"',
      '    android:height="108dp"',
      '    android:viewportWidth="108"',
      '    android:viewportHeight="108">',
      '    <path',
      '        android:fillColor="' + color + '"',
      '        android:pathData="M0,0h108v108h-108z" />',
      '    <path',
      '        android:fillColor="#FFFFFF"',
      '        android:pathData="M30,30h48v48h-48z" />',
      '</vector>',
    ].join('\n'),
  );
}

(async () => {
  try {
    fs.rmSync('app', { recursive: true, force: true });
  } catch {
    /* ignore */
  }
  // Clean any leftover root gradle files from previous runs on the runner workspace
  for (const f of [
    'settings.gradle',
    'build.gradle',
    'gradle.properties',
    'local.properties',
    'gradlew',
    'gradlew.bat',
  ]) {
    try {
      fs.rmSync(f, { force: true });
    } catch {
      /* ignore */
    }
  }
  try {
    fs.rmSync('gradle', { recursive: true, force: true });
  } catch {
    /* ignore */
  }

  logoDownloaded = await downloadLogoIcon();

  writeText(
    'settings.gradle',
    [
      'pluginManagement {',
      '    repositories {',
      '        google()',
      '        mavenCentral()',
      '        gradlePluginPortal()',
      '    }',
      '}',
      'dependencyResolutionManagement {',
      '    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)',
      '    repositories {',
      '        google()',
      '        mavenCentral()',
      '    }',
      '}',
      "rootProject.name = 'MangaApp'",
      "include ':app'",
    ].join('\n'),
  );

  writeText(
    'build.gradle',
    [
      'plugins {',
      "    id 'com.android.application' version '" + AGP_VERSION + "' apply false",
      '}',
    ].join('\n'),
  );

  writeText(
    'gradle.properties',
    [
      'org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m',
      'org.gradle.parallel=false',
      'org.gradle.caching=true',
      'org.gradle.configureondemand=false',
      'org.gradle.daemon=false',
      'org.gradle.workers.max=1',
      'android.useAndroidX=true',
      'android.nonTransitiveRClass=true',
    ].join('\n'),
  );

  writeText(
    'gradle/wrapper/gradle-wrapper.properties',
    [
      'distributionBase=GRADLE_USER_HOME',
      'distributionPath=wrapper/dists',
      'distributionUrl=https\\://services.gradle.org/distributions/gradle-' +
        GRADLE_VERSION +
        '-bin.zip',
      'networkTimeout=60000',
      'validateDistributionUrl=true',
      'zipStoreBase=GRADLE_USER_HOME',
      'zipStorePath=wrapper/dists',
    ].join('\n'),
  );

  const sdkDir = String(process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT || '').replace(
    /\\/g,
    '\\\\',
  );
  if (sdkDir) {
    writeText('local.properties', 'sdk.dir=' + sdkDir);
  } else {
    console.warn('ANDROID_HOME not set at generate time — Gradle will use env on build.');
  }

  writeText(
    'app/build.gradle',
    [
      'plugins {',
      "    id 'com.android.application'",
      '}',
      '',
      'android {',
      "    namespace '" + pkg + "'",
      '    compileSdk ' + compileSdk,
      '',
      '    defaultConfig {',
      "        applicationId '" + pkg + "'",
      '        minSdk ' + minSdk,
      '        targetSdk ' + targetSdk,
      '        versionCode ' + versionCode,
      "        versionName '" + versionName + "'",
      '    }',
      '',
      '    signingConfigs {',
      '        release {',
      '            initWith debug',
      '        }',
      '    }',
      '',
      '    buildTypes {',
      '        release {',
      '            minifyEnabled false',
      '            shrinkResources false',
      '            debuggable false',
      '            signingConfig signingConfigs.release',
      '        }',
      '        debug {',
      '            minifyEnabled false',
      '            debuggable true',
      '        }',
      '    }',
      '',
      '    compileOptions {',
      '        sourceCompatibility JavaVersion.VERSION_17',
      '        targetCompatibility JavaVersion.VERSION_17',
      '    }',
      '',
      '    packaging {',
      '        resources {',
      "            excludes += ['/META-INF/{AL2.0,LGPL2.1}', 'META-INF/DEPENDENCIES']",
      '        }',
      '    }',
      '',
      '    lint {',
      '        checkReleaseBuilds false',
      '        abortOnError false',
      '    }',
      '}',
      '',
      'dependencies {',
      "    implementation 'androidx.appcompat:appcompat:1.6.1'",
      "    implementation 'androidx.webkit:webkit:1.8.0'",
      '}',
    ].join('\n'),
  );

  writeText(
    'app/proguard-rules.pro',
    '# WebView\n-keepclassmembers class * {\n    @android.webkit.JavascriptInterface <methods>;\n}\n',
  );

  // Icon reference: mipmap if PNG installed, else drawable vector
  const iconRef = logoDownloaded ? '@mipmap/ic_launcher' : '@drawable/ic_launcher';

  writeText(
    'app/src/main/AndroidManifest.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<manifest xmlns:android="http://schemas.android.com/apk/res/android">',
      '',
      '    <uses-permission android:name="android.permission.INTERNET" />',
      '    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />',
      '',
      '    <application',
      '        android:allowBackup="true"',
      '        android:icon="' + iconRef + '"',
      '        android:roundIcon="' + iconRef + '"',
      '        android:label="@string/app_name"',
      '        android:supportsRtl="true"',
      '        android:theme="@style/Theme.MangaApp"',
      '        android:usesCleartextTraffic="true">',
      '',
      '        <activity',
      '            android:name=".MainActivity"',
      '            android:exported="true"',
      '            android:configChanges="orientation|screenSize|keyboardHidden|screenLayout|smallestScreenSize"',
      '            android:launchMode="singleTask"',
      '            android:windowSoftInputMode="adjustResize">',
      '            <intent-filter>',
      '                <action android:name="android.intent.action.MAIN" />',
      '                <category android:name="android.intent.category.LAUNCHER" />',
      '            </intent-filter>',
      '        </activity>',
      '    </application>',
      '</manifest>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/values/strings.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <string name="app_name">' + xmlEscape(appName) + '</string>',
      '</resources>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/values/colors.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <color name="primary">' + color + '</color>',
      '    <color name="black">#FF000000</color>',
      '    <color name="white">#FFFFFFFF</color>',
      '</resources>',
    ].join('\n'),
  );

  writeText(
    'app/src/main/res/values/themes.xml',
    [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <style name="Theme.MangaApp" parent="Theme.AppCompat.DayNight.NoActionBar">',
      '        <item name="colorPrimary">@color/primary</item>',
      '        <item name="colorPrimaryDark">@color/primary</item>',
      '        <item name="colorAccent">@color/primary</item>',
      '        <item name="android:statusBarColor">@color/primary</item>',
      '        <item name="android:navigationBarColor">@color/black</item>',
      '        <item name="android:windowBackground">@color/black</item>',
      '    </style>',
      '</resources>',
    ].join('\n'),
  );

  // Only ONE ic_launcher resource family (PNG mipmap XOR vector drawable)
  if (!logoDownloaded) {
    writeVectorIcon();
  }

  writeText(
    'app/src/main/java/' + pkgPath + '/MainActivity.java',
    [
      'package ' + pkg + ';',
      '',
      'import android.annotation.SuppressLint;',
      'import android.os.Bundle;',
      'import android.webkit.WebChromeClient;',
      'import android.webkit.WebSettings;',
      'import android.webkit.WebView;',
      'import android.webkit.WebViewClient;',
      'import androidx.appcompat.app.AppCompatActivity;',
      '',
      'public class MainActivity extends AppCompatActivity {',
      '    private WebView webView;',
      '',
      '    @Override',
      '    @SuppressLint("SetJavaScriptEnabled")',
      '    protected void onCreate(Bundle savedInstanceState) {',
      '        super.onCreate(savedInstanceState);',
      '        webView = new WebView(this);',
      '        setContentView(webView);',
      '',
      '        WebSettings settings = webView.getSettings();',
      '        settings.setJavaScriptEnabled(true);',
      '        settings.setDomStorageEnabled(true);',
      '        settings.setLoadWithOverviewMode(true);',
      '        settings.setUseWideViewPort(true);',
      '        settings.setSupportZoom(false);',
      '        settings.setBuiltInZoomControls(false);',
      '        settings.setDisplayZoomControls(false);',
      '        settings.setMediaPlaybackRequiresUserGesture(false);',
      '        settings.setAllowFileAccess(false);',
      '        settings.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);',
      '        settings.setCacheMode(WebSettings.LOAD_DEFAULT);',
      '',
      '        webView.setWebViewClient(new WebViewClient());',
      '        webView.setWebChromeClient(new WebChromeClient());',
      '        webView.loadUrl("' + safeUrl + '");',
      '    }',
      '',
      '    @Override',
      '    @SuppressWarnings("deprecation")',
      '    public void onBackPressed() {',
      '        if (webView != null && webView.canGoBack()) {',
      '            webView.goBack();',
      '        } else {',
      '            super.onBackPressed();',
      '        }',
      '    }',
      '',
      '    @Override',
      '    protected void onDestroy() {',
      '        if (webView != null) {',
      '            webView.destroy();',
      '            webView = null;',
      '        }',
      '        super.onDestroy();',
      '    }',
      '}',
    ].join('\n'),
  );

  // Sanity checks before handing off to Gradle
  const mustExist = [
    'settings.gradle',
    'build.gradle',
    'app/build.gradle',
    'app/src/main/AndroidManifest.xml',
    'app/src/main/res/values/strings.xml',
    'app/src/main/res/values/themes.xml',
    'app/src/main/java/' + pkgPath + '/MainActivity.java',
  ];
  for (const f of mustExist) {
    if (!fs.existsSync(f)) {
      console.error('Missing required file after generate:', f);
      process.exit(1);
    }
  }
  const hasIcon =
    fs.existsSync('app/src/main/res/mipmap-hdpi/ic_launcher.png') ||
    fs.existsSync('app/src/main/res/drawable/ic_launcher.xml');
  if (!hasIcon) {
    console.warn('No icon found — writing emergency vector');
    writeVectorIcon();
  }

  console.log(
    'Android project generated for ' +
      pkg +
      ' v' +
      versionName +
      ' (' +
      versionCode +
      ') url=' +
      websiteUrl +
      (logoDownloaded ? ' icon=website-logo-mipmap' : ' icon=vector-fallback') +
      ' agp=' +
      AGP_VERSION +
      ' gradle=' +
      GRADLE_VERSION,
  );
})().catch((e) => {
  console.error('gen-android failed:', e);
  process.exit(1);
});
